-- auto Generated on 2019-06-09 22:29:38 
-- DROP TABLE IF EXISTS `error_log`; 
CREATE TABLE error_log(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `log_tag` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'LOG TAG',
    `log_msg` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'LOG信息',
    `log_time` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'LOG时间',
    `log_status` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '日志状态 0DEBUG 1INFO 2WARN 3ERROR',
    `is_deleted` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '删除标记',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'error_log';
